import secrets
import requests
import json 

auth_token = secrets.token_hex(16) 


API_URL = "https://jsonplaceholder.typicode.com/posts/1"

# Simulate sending the generated token in the Authorization header
headers = {
    "User-Agent": "MySecureClientApp/1.0",
    "Authorization": f"Bearer {auth_token}" # The token generated by secrets is used here
}

try:
    api_response = requests.get(API_URL, headers=headers, timeout=5)
    
    if api_response.status_code == 200:
        api_data = api_response.json()
        api_status = "SUCCESS"
    else:
        api_data = f"HTTP Error: Status {api_response.status_code}"
        api_status = "FAILURE"

except requests.exceptions.RequestException as e:
    api_data = f"Network Error: {e}"
    api_status = "FAILURE"

print("=" * 60)
print("SECRETS MODULE RESULT (Local Generation)")
print(f"Generated Authorization Token (256 bits): {auth_token}")

print("-" * 60)
print("REQUESTS MODULE RESULT (External Request)")
print(f"API Request Status: {api_status}")

if api_status == "SUCCESS":
    print("API Response Details (Post ID 1):")
    print(json.dumps(api_data, indent=4))
else:
    print(f"Failure Message: {api_data}")

print("=" * 60)